using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Org.BouncyCastle.Bcpg.Sig;
using ReactApp2.Server.Models;

namespace ReactApp2.Server.Data
{
    public class ApplicationDbContext : IdentityDbContext<IdentityUser>
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options) :
            base(options)
        {
        }
        public DbSet<Product> Products { get; set; }
        public DbSet<ApplicationUser> User { get; set; }
        public DbSet<Details> Details { get; set; }
        public DbSet<Category> Categories { get; set; }
        public DbSet<Featured> Featureds { get; set; }
        public DbSet<Checkout> Checkouts { get; set; }
        public DbSet<ProductCheck> ProductCheckout { get; set; }
        public DbSet<Delivery> Deliveries { get; set; }
        public DbSet<OptionsStructure> optionsStructures { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Entity<Product>()
                .HasOne(p => p.Category)
                .WithMany()
                .HasForeignKey(p => p.CategoryId)
                .OnDelete(DeleteBehavior.Restrict); // Ensure no cascade delete
            modelBuilder.Entity<OptionsStructure>()
             .Property(o => o.Id)
             .ValueGeneratedOnAdd(); // Ensures Id is autogenerated by the database

            // Other configurations...
        }
    }
}
